export const BlogPosts = [
  {
    id: 0,
    title: "My new journey as a bootcamp student.",
    content: `After several months of learning in the Frontend Developer Career Path, I've made the big jump over to the Bootcamp to get expert code reviews of my Solo Projects projects and meet like-minded peers.`,
    date: "2020-01-01",
    image: "/images/hero-image.png",
  },
  {
    id: 1,
    title: "Tips for mastering CSS Grid and Flexbox.",
    content: `CSS Grid and Flexbox are powerful tools for layout design. Combining them can help create responsive designs more effectively. Here are some tips and tricks I've learned along the way.`,
    date: "2020-02-15",
    image: "/images/blog-image-01.png",
  },
  {
    id: 2,
    title: "Building my first React application.",
    content: `I finally built my first React app! It’s a simple to-do list, but it helped me grasp the basics of components, state, and props.`,
    date: "2020-03-10",
    image: "/images/blog-image-02.png",
  },
  {
    id: 3,
    title: "Why JavaScript is my favorite language.",
    content: `JavaScript allows me to bring my ideas to life, from dynamic front-end features to powerful back-end services. Here's why I love it so much.`,
    date: "2020-04-05",
    image: "/images/blog-image-03.png",
  },
  {
    id: 4,
    title: "Understanding RESTful APIs with a practical example.",
    content: `I recently learned about RESTful APIs and implemented a small project to fetch and display data from an API. Here's how I did it.`,
    date: "2020-05-20",
    image: "/images/blog-image-04.png",
  },
  {
    id: 5,
    title: "Debugging tips for JavaScript developers.",
    content: `Debugging can be tricky, but tools like Chrome DevTools and techniques like logging have made it easier for me. Here’s what has worked for me so far.`,
    date: "2020-06-12",
    image: "/images/blog-image-05.png",
  },
  {
    id: 6,
    title: "My experience with building responsive web designs.",
    content: `Creating designs that look great on all devices is both challenging and rewarding. Here's how I approach building mobile-first responsive websites.`,
    date: "2020-07-01",
    image: "/images/blog-image-06.png",
  },
];
